- name: variables from files
  hosts: local
  connection: local
  vars-files:
  - course.yaml
  tasks:
  - name: print course info
    ansible.builtin.debug:
      msg: "Course is: {{ COURSE }}, Duration is: {{ DURATION }}, Trainer is: {{ TRAINER }}"
      