- name: variables from prompt
  hosts: local
  connection: local
  vars_prompt:
  - name: username
    prompt: Enter username
    private: false
  - name: password
    prompt: Enter password
    private: true
  tasks:
  - name: print course info
    ansible.builtin.debug:
      msg: "Hello, username is: {{ username }}, password is: {{ password }}"