- name: install package using loops
  hosts: local
  connection: local
  become: yes
  tasks:
    - name: print names
      ansible.builtin.package:
        name: "{{ item }}"
        state: latest 
      loop:
        - nginx
        - nodejs
        - zip
